* Agentes Calidad del Aire
** Justificación
   Medellín tiene un problema de calidad del aire, la política pública tiene planes a largo plazo, el sistema publico de monitoreo de calidad del aire tiene alcance limitado. 
** Problema
   El ciudadano no tiene una medición del aire que respira en el momento. 
** Solución propuesta
   Medidor portable que indique visualmente la calidad del aire y que permita socializar esas mediciones.
** Fases
*** Primer fase: 
**** Puntos fijos
**** con plataforma web de captura de datos,
**** alimentación de energía 
**** transmisión vía WiFi
**** (Opción almacenaje de datos en SD?)
**** Uso de los datos:
***** a. Publicación de dataset (Open Data), sin procesamiento o con depuración??
***** b. Publicación básica de resultados en web responsive, en mapas y capas de análisis básico.
***  Segunda Fase: 
**** Puntos móviles con gps (Batería, 
**** transmisión vía WiFi o SimCard?, 
**** (opción de almacenar en SD).
**** Uso de los datos:
***** a. Publicación de dataset (Open Data), sin procesamiento o con depuración??
***** b. Publicación básica de resultados en web responsive, en mapas y capas de análisis básico.
***** c. Desarrollo de aplicación móvil (Android, posiblemente ios).

